/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteRouteImport } from './routes/architecture/route'
import { Route as CredentialsRouteRouteImport } from './routes/credentials/route'
import { Route as RobotsDottxtRouteRouteImport } from './routes/robots[.]txt/route'
import { Route as StyleRouteRouteImport } from './routes/style/route'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRouteRoute = ArchitectureRouteRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRouteRoute = CredentialsRouteRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRouteRoute = RobotsDottxtRouteRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleRouteRoute = StyleRouteRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRouteRoute
  '/credentials': typeof CredentialsRouteRoute
  '/robots.txt': typeof RobotsDottxtRouteRoute
  '/style': typeof StyleRouteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRouteRoute
  '/credentials': typeof CredentialsRouteRoute
  '/robots.txt': typeof RobotsDottxtRouteRoute
  '/style': typeof StyleRouteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRouteRoute
  '/credentials': typeof CredentialsRouteRoute
  '/robots.txt': typeof RobotsDottxtRouteRoute
  '/style': typeof StyleRouteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/credentials'
    | '/robots.txt'
    | '/style'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/credentials'
    | '/robots.txt'
    | '/style'
    | '/projects/$projectId'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/credentials'
    | '/robots.txt'
    | '/style'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRouteRoute: typeof ArchitectureRouteRoute
  CredentialsRouteRoute: typeof CredentialsRouteRoute
  RobotsDottxtRouteRoute: typeof RobotsDottxtRouteRoute
  StyleRouteRoute: typeof StyleRouteRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRouteRoute: ArchitectureRouteRoute,
  CredentialsRouteRoute: CredentialsRouteRoute,
  RobotsDottxtRouteRoute: RobotsDottxtRouteRoute,
  StyleRouteRoute: StyleRouteRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
